# Generated by Django 4.2.13 on 2024-10-08 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("solax_registers", "0004_lastminutestatsrecord_grid_power_r_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastminutestatsrecord",
            name="inverter_voltage_r",
        ),
        migrations.RemoveField(
            model_name="lastminutestatsrecord",
            name="inverter_voltage_s",
        ),
        migrations.RemoveField(
            model_name="lastminutestatsrecord",
            name="inverter_voltage_t",
        ),
        migrations.RemoveField(
            model_name="minutestatsrecord",
            name="inverter_voltage_r",
        ),
        migrations.RemoveField(
            model_name="minutestatsrecord",
            name="inverter_voltage_s",
        ),
        migrations.RemoveField(
            model_name="minutestatsrecord",
            name="inverter_voltage_t",
        ),
    ]
