name: Django CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-with-python-38:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        django-version: ["4.2"]

    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.8"
          django-version: ${{ matrix.django-version }}

  test-with-python-39:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        django-version: ["4.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.9"
          django-version: ${{ matrix.django-version }}

  test-with-python-310:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        django-version: ["4.2", "5.0", "5.1", "5.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.10"
          django-version: ${{ matrix.django-version }}

  test-with-python-311:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        django-version: ["4.2", "5.0", "5.1", "5.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.11"
          django-version: ${{ matrix.django-version }}

  test-with-python-312:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        django-version: ["4.2", "5.0", "5.1", "5.2", "6.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.12"
          django-version: ${{ matrix.django-version }}

  test-with-python-313:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        django-version: ["5.1", "5.2", "6.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.13"
          django-version: ${{ matrix.django-version }}

  test-with-python-314:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        django-version: ["5.2", "6.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: "3.14"
          django-version: ${{ matrix.django-version }}

  test-with-latest-django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Test API gateway
        uses: mkfam7/test_solaxx3_api_action@main
        with:
          python-version: ${{ matrix.python-version }}
          test-latest: true
